### ISSUE TITLE
Dynamic creation of TTS

### ISSUE THREAD

**Issue by patarapolw** [mrf345/flask_gtts#1]
I would like to see dynamic creation of TTS, like on mouse-click, or on mouse-over. That would help with language vocab learning, like from a dictionary.

**Comment by mrf345** [comment]
Hi  @patarapolw , There's a `route` option which's `False` by default, If you make it true, a new route `/gtts/<language>/<text>` will be opened. From there you'll have to do some javascripting, Example: 
```javascript
document.getElementById('sayit')
.addEventListener('click', (e) => {
    fetch(
        window.location.origin + 
        '/gtts/en-us/' + 
        String(document.getElementById('sayit').innerText)
    ).then(function (r) {
        return r.json()
    }).then(function (j) {
        let a = document.createElement('AUDIO')
        a.src = window.location.origin + j.mp3
        a.play()
    }).catch(function (e) {
        console.warn(e)
    })
})
```
Do you think, i should include the JS as an option to the extension ?
I have updated [example.py](https://github.com/mrf345/flask_gtts/blob/master/example.py) to include this example.

**Comment by patarapolw** [comment]
I mean "something to say" itself is dynamic, so

    function speak(item){
      fetch(
        window.location.origin +
        '/gtts/zh-cn/' +
        item
      ).then(function(r){
        return r.json();
      }).then(function(j){
        let a = document.createElement('AUDIO');
        a.src = window.location.origin + j.mp3;
        a.play();
      }).catch(function(e){
        console.warn(e);
      });
    }

without declaring `{{sayit("en-us","something to say")}}`

Error:

```
Traceback (most recent call last):
  File "/Users/patarapolw/.local/share/virtualenvs/ChineseViewer-NIGPzld1/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/patarapolw/.local/share/virtualenvs/ChineseViewer-NIGPzld1/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/patarapolw/.local/share/virtualenvs/ChineseViewer-NIGPzld1/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/patarapolw/.local/share/virtualenvs/ChineseViewer-NIGPzld1/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/patarapolw/.local/share/virtualenvs/ChineseViewer-NIGPzld1/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/patarapolw/.local/share/virtualenvs/ChineseViewer-NIGPzld1/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/patarapolw/.local/share/virtualenvs/ChineseViewer-NIGPzld1/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/patarapolw/.local/share/virtualenvs/ChineseViewer-NIGPzld1/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/patarapolw/.local/share/virtualenvs/ChineseViewer-NIGPzld1/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/patarapolw/.local/share/virtualenvs/ChineseViewer-NIGPzld1/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/patarapolw/.local/share/virtualenvs/ChineseViewer-NIGPzld1/lib/python3.6/site-packages/flask_gtts/__init__.py", line 90, in gttsRoute
    text.encode('utf8')
  File "/Users/patarapolw/.local/share/virtualenvs/ChineseViewer-NIGPzld1/lib/python3.6/site-packages/flask_gtts/__init__.py", line 54, in say
    raise(TypeError("gtts.say(%s) takes string" % h))
TypeError: gtts.say(lang) takes string
```

**Comment by mrf345** [comment]
Hi @patarapolw, probably you got confused. I meant `route=True` option inside the Flask app:
```python
app = Flask(__name__)
gtts(app=app, route=True)
```
With this option enabled a new route will be open on `http://localhost/gtts/<language>/<text>`
which will return JSON response `{mp3: 'link to the mp3 file'}`. So now there's no need for {{ say() }}
you can use javascript to `fetch()` and play the mp3 file.

**Comment by mrf345** [comment]
I added new release 0.7 with this feature. First update it `pip install -U flask_gtts`. Example:
```jinja
<head>
  {{ read(id='.readIt') }}
</head>
<body>
  <h1 class='readIt'>Say something</h1>
  <h1 class='readIt' language='it'>qualcosa da dire</h1>
</body>
```
If mouseover instead of click do `{{ read(id='.readIt', mouseover=True) }}`
